### ISSUE TITLE
init script shows error even though successful

### ISSUE THREAD

**Issue by thgh** [Testy/TestyTs#94]
`testy.json` was created even though this error is printed in the console:
```
» yarn add testyts -D
...
✨  Done in 3.13s.
» npx testyts init
/path/to/project/node_modules/testyts/build/lib/utils/jsonLoader.service.js:21
                throw new Error(`The specified configuration file could not be found: ${path}`);
                      ^

Error: The specified configuration file could not be found: /path/to/project/testy.json
    at JsonLoader.<anonymous> (/path/to/project/node_modules/testyts/build/lib/utils/jsonLoader.service.js:21:23)
    at Generator.next (<anonymous>)
    at /path/to/project/node_modules/testyts/build/lib/utils/jsonLoader.service.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/path/to/project/node_modules/testyts/build/lib/utils/jsonLoader.service.js:4:12)
    at JsonLoader.load (/path/to/project/node_modules/testyts/build/lib/utils/jsonLoader.service.js:18:16)
    at TestyCli.<anonymous> (/path/to/project/node_modules/testyts/build/lib/cli/testyCli.js:50:55)
    at Generator.next (<anonymous>)
    at /path/to/project/node_modules/testyts/build/lib/cli/testyCli.js:8:71
    at new Promise (<anonymous>)

Node.js v17.0.1
» ls testy.json
testy.json
» npx testyts init # no output when run a second time
»
```

This is on macos

**Comment by Aboisier** [comment]
Hi! Thanks for reporting this issue. It was fixed in version 2.0.0-beta.7.
